name: Build & Deploy

on:
  push:
    branches:
      - master  # Adjust branch name as per your main branch

jobs:
  build-deploy:
    name: Build & Deploy RM Pro Spring App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Build the application using Maven
      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      # Step 4: Get current date and time in IST
      - name: Get current date and time in IST
        id: vars
        run: |
          IST_DATE=$(TZ='Asia/Kolkata' date +'%Y%m%d%H%M%S')
          echo "TAG=$IST_DATE" >> $GITHUB_ENV

      # Step 5: Build Docker Image
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile  # Adjust Dockerfile path if necessary
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rmmanagement:${{ env.TAG }}

      # Step 6: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 7: Push Docker Image to Docker Hub
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile  # Adjust Dockerfile path if necessary
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rmmanagement:${{ env.TAG }}

      # Step 8: Deploy to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/rmmanagement:${{ env.TAG }}
            docker stop RMManagement || true
            docker rm RMManagement || true
            docker run -d --name RMManagement -p 8446:8446 ${{ secrets.DOCKER_HUB_USERNAME }}/rmmanagement:${{ env.TAG }}
